INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (1, 1, 1, '00:05:30');
INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (1, 2, 3, '00:05:46');
INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (1, 3, 2, '00:05:44');
INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (1, 4, 5, '00:06:01');
INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (1, 5, 4, '00:05:50');
INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (1, 6, 8, '00:06:34');
INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (1, 7, 6, '00:06:03');
INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (1, 8, 7, '00:06:32');
INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (1, 9, 9, '00:06:35');
INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (1, 10, 10, '00:06:40');

INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (2, 1, 7, '00:10:45');
INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (2, 2, 4, '00:10:34');
INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (2, 3, 5, '00:10:35');
INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (2, 4, 6, '00:10:40');
INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (2, 5, 10, '00:11:10');
INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (2, 6, 2, '00:10:32');
INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (2, 7, 3, '00:10:33');
INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (2, 8, 8, '00:10:47');
INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (2, 9, 9, '00:11:00');
INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (2, 10, 1, '00:10:30');

INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (3, 1, NULL , NULL );
INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (3, 2, NULL , NULL );
INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (3, 3, NULL , NULL );
INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (3, 4, NULL , NULL );
INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (3, 5, NULL , NULL );
INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (3, 6, NULL , NULL );
INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (3, 7, NULL , NULL );
INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (3, 8, NULL , NULL );
INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (3, 9, NULL , NULL );
INSERT INTO `horse_race` (`raceID`, `horseID`, `result_rank`, `result_time`) VALUES (3, 10, NULL , NULL );
